TEMP WIP After many changes

diff --git a/gswitch b/gswitch
--- a/gswitch
+++ b/gswitch
@@ -7,56 +7,53 @@ if [ "$(whoami)" != "root" ]; then
  exit
 fi
 
-OS=$(lsb_release -a 2>/dev/null | awk '/Distributor ID:/{print tolower($NF)}')
-
-case "${OS}" in
-  opensuse)
-    XORG_CONF_DIR="/etc/X11/xorg.conf.d"
-    if [ ! -d "${XORG_CONF_DIR}" ]; then
-      mkdir -p "${XORG_CONF_DIR}"
-    fi
-    EGPU_TEMPLATE="${XORG_CONF_DIR}/xorg.conf.egpu"
-    XORG_CONFIG="${XORG_CONF_DIR}/99-gswitch-egpu.conf"
-  ;;
-  ubuntu)
-    XORG_CONF_DIR="/etc/X11"
-    if [ ! -d "${XORG_CONF_DIR}" ]; then
-      mkdir -p "${XORG_CONF_DIR}"
-    fi
-    EGPU_TEMPLATE="${XORG_CONF_DIR}/xorg.conf.egpu"
-    XORG_CONFIG="${XORG_CONF_DIR}/xorg.conf"
-  ;;
-  *)
-    # Untested OS distribution
-    # Hoping the path works the all the same
-    XORG_CONF_DIR="/etc/X11/xorg.conf.d"
-    if [ ! -d "${XORG_CONF_DIR}" ]; then
-      mkdir -p "${XORG_CONF_DIR}"
-    fi
-    EGPU_TEMPLATE="${XORG_CONF_DIR}/xorg.conf.egpu"
-    XORG_CONFIG="${XORG_CONF_DIR}/99-gswitch-egpu.conf"
-  ;;
-esac
-
-if [ -f "${EGPU_TEMPLATE}" ]; then
-  EGPU_BUS_ID=$(awk '/BusID/{gsub(/(PCI:|\")/," ");print$2}' \
-                < "${EGPU_TEMPLATE}" 2>/dev/null)
-  # TODO May need awk fix seen in other forks
-  XORG_DRIVER=$(awk '/Driver/{gsub("\"","");if($1 != "#")print$2}' \
-                < "${EGPU_TEMPLATE}" 2>/dev/null)
-fi
-if [ "$(echo "${XORG_DRIVER}" | wc -w)" -gt "1" ]; then
-  echo "More than one driver specified in the template. Exiting."
-  exit 1
+XORG_CONF_DIR="/etc/X11/xorg.conf.d"
+if [ ! -d "${XORG_CONF_DIR}" ]; then
+  mkdir -p "${XORG_CONF_DIR}"
 fi
 
-if [ -h "${XORG_CONFIG}" ] && \
-   [ -f "${EGPU_TEMPLATE}" ] && \
-   [ "$(readlink "${XORG_CONFIG}")" = "${EGPU_TEMPLATE}" ]; then
-  EGPU_SET="true"
-else
-  EGPU_SET="false"
-fi
+# HOST_GPU_VIDEO_BUS_ID="03:00.0"
+# HOST_GPU_AUDIO_BUS_ID="03:00.1"
+# GUEST_GPU_VIDEO_BUS_ID="01:00.0"
+# GUEST_GPU_AUDIO_BUS_ID="01:00.1"
+
+XORG_HOST_GPU_CONF="${XORG_CONF_DIR}/99-gswitch-host.conf"
+XORG_GUEST_GPU_CONF="${XORG_CONF_DIR}/99-gswitch-guest.conf"
+
+source ./gswitch.conf
+
+# Example: "0b:00.1" -> "11:0:1"
+hex_bus_id_to_dec_id() {
+  local hex_id=$1
+  local dec_id hex_value
+  for hex_value in $(echo "${hex_id}" | tr ':|\.' ' '); do
+    local hex_value_upper=$(echo "${hex_value}" | tr '[:lower:]' '[:upper:]')
+    local dec_value=$(echo "ibase=16; ${hex_value_upper}" | bc)
+    if [ "${dec_id}" != "" ]; then
+      dec_id="${dec_id}:"
+    fi
+    dec_id="${dec_id}${dec_value}"
+  done
+  echo $dec_id
+}
+
+has_xorg_confs_setup() {
+  [[
+    ((-f "${XORG_HOST_GPU_CONF}") || (-f "${XORG_HOST_GPU_CONF}.skip"))
+    && ((-f "${XORG_GUEST_GPU_CONF}") || (-f "${XORG_GUEST_GPU_CONF}.skip"))
+  ]]
+  return
+}
+
+active_xorg_conf() {
+  if [ -f "${XORG_HOST_GPU_CONF}" ]; then
+    echo "host"
+  elif [ -f "${XORG_GUEST_GPU_CONF}" ]; then
+    echo "guest"
+  else
+    echo ""
+  fi
+}
 
 ask_reload() {
   QUESTION=$1
@@ -77,13 +74,14 @@ ask_reload() {
 }
 
 do_reload() {
+  local target_gpu = $1 # "host" | "guest"
   ( trap '' HUP TERM
     while [ "$(systemctl status display-manager | awk '/Active:/{print$2}')" \
                = "active" ]; do
       sleep 1
     done
-    killall gdm-x-session
-    sleep 4
+    # killall gdm-x-session
+    # sleep 4
     if [ "${REMOVE}" = "true" ]; then
       for PATH_D in ${DEV_PATH}; do
         if [ -e "${PATH_D}" ]; then
@@ -91,37 +89,26 @@ do_reload() {
         fi
       done
     fi
-    if [ "${SWITCHING_EGPU}" = "true" ]; then
-      bind_nvidia
+    if [ "${target_gpu}" = "guest" ]; then
+      bind_guest_gpu_driver
+    else
+      bind_guest_gpu_vfio_pci
     fi
-    if [ "$(lspci -k | grep -c "${XORG_DRIVER}")" -gt 0 ]; then
-      modprobe "${XORG_DRIVER}"
-      # if [ "${XORG_DRIVER}" = "nvidia" ]; then
-      #   modprobe nvidia_drm
-      # fi
+    if [ "$(lspci -k | grep -c "${GUEST_GPU_DRIVER}")" -gt 0 ]; then
+      modprobe "${GUEST_GPU_DRIVER}"
+      if [ "${GUEST_GPU_DRIVER}" = "nvidia" ]; then
+        modprobe nvidia_drm
+      fi
     fi
     systemctl start display-manager.service ) &
   systemctl stop display-manager.service
   exit 0
 }
 
-switch_egpu() {
-  SWITCHING_EGPU="true"
-  if [ ! -f "${EGPU_TEMPLATE}" ]; then
-    echo "No eGPU template detected, please run setup before use:"
-    echo "# gswitch setup"
-    exit 1
-  fi
-  if [ "${XORG_DRIVER}" != "nvidia" ]; then
+switch_to_guest_gpu() {
+  if [ "${GUEST_GPU_DRIVER}" != "nvidia" ]; then
     for HEX_ID in $(lspci | grep -i 'vga' | cut -f 1 -d ' '); do
-      DEC_ID=""
-      for HEX_VALUE in $(echo "${HEX_ID}" | tr ':|\.' ' '); do
-        HEX_VALUE_UPPER=$(echo "${HEX_VALUE}" | tr '[:lower:]' '[:upper:]')
-        DEC_VALUE=$(echo "ibase=16; ${HEX_VALUE_UPPER}" | bc)
-        DEC_ID="${DEC_ID}:${DEC_VALUE}"
-      done
-      DEC_ID=$(echo "${DEC_ID}" | sed 's/^://')
-      if [ "${DEC_ID}" = "${EGPU_BUS_ID}" ]; then
+      if [ "${DEC_ID}" = "${GUEST_GPU_VIDEO_BUS_ID}" ]; then
         break
       fi
     done
@@ -136,60 +123,51 @@ switch_egpu() {
       echo "Warning: No eGPU attached display detected with open source drivers."
       echo "Internal mode and setting DRI_PRIME variable are recommended for this configuration."
       echo "Not setting eGPU mode."
-      switch_internal
+      switch_to_host_gpu
       exit 0
     fi
   fi
-  if [ "${EGPU_SET}" = "true" ]; then
+  if has_xorg_confs_setup; then
     ask_reload "You are already set up. Would you like to reload? (Y/n)"
     if [ "${RELOAD}" = "true" ]; then
-      do_reload
+      do_reload "guest"
     else
       exit 0
     fi
   else
-    # TODO
-    rm /etc/X11/xorg.conf.d/99-gswitch-igpu.conf
+    mv "${XORG_HOST_GPU_CONF}" "${XORG_HOST_GPU_CONF}.skip"
+    mv "${XORG_GUEST_GPU_CONF}.skip" "${XORG_GUEST_GPU_CONF}.skip"
 
-    ln -s "${EGPU_TEMPLATE}" "${XORG_CONFIG}"
     ask_reload "You are now set up. Would you like to reload? (Y/n)"
     if [ "${RELOAD}" = "true" ]; then
-      do_reload
+      do_reload "guest"
     else
       exit 0
     fi
   fi
 }
 
-switch_internal() {
-  SWITCHING_EGPU="false"
-  if [ ! -f "${EGPU_TEMPLATE}" ]; then
-    echo "No eGPU template detected, please run setup before use:"
-    echo "# gswitch setup"
-    exit 1
-  fi
-  if [ "${EGPU_SET}" = "true" ]; then
-    rm -f "${XORG_CONFIG}"
+switch_to_host_gpu() {
+  if [ "$(active_xorg_conf)" != "host" ]; then
+    mv "${XORG_HOST_GPU_CONF}.skip" "${XORG_HOST_GPU_CONF}"
+    mv "${XORG_GUEST_GPU_CONF}" "${XORG_GUEST_GPU_CONF}.skip"
     ask_reload "You are now set up. Would you like to reload? (Y/n)"
     if [ "${RELOAD}" = "true" ]; then
-      do_reload
+      do_reload "host"
     else
       exit 0
     fi
   else
     ask_reload "You are already set up. Would you like to reload? (Y/n)"
     if [ "${RELOAD}" = "true" ]; then
-      do_reload
+      do_reload "host"
     else
       exit 0
     fi
   fi
 }
 
-GPU_VIDEO_1="0000:01:00.0"
-GPU_AUDIO_1="0000:01:00.1"
-
-bind_vfio_pci() {
+bind_guest_gpu_vfio_pci() {
   # Unbind VTconsoles
   echo 0 > /sys/class/vtconsole/vtcon0/bind
   echo 0 > /sys/class/vtconsole/vtcon1/bind
@@ -202,8 +180,8 @@ bind_vfio_pci() {
 
   ### DRIVER BINDINGS
   # GPU 1 unbind from nvidia
-  echo "$GPU_VIDEO_1" > /sys/bus/pci/devices/$GPU_VIDEO_1/driver/unbind
-  echo "$GPU_AUDIO_1" > /sys/bus/pci/devices/$GPU_AUDIO_1/driver/unbind
+  echo "$GUEST_GPU_VIDEO_BUS_ID" > /sys/bus/pci/devices/$GUEST_GPU_VIDEO_BUS_ID/driver/unbind
+  echo "$GUEST_GPU_AUDIO_BUS_ID" > /sys/bus/pci/devices/$GUEST_GPU_AUDIO_BUS_ID/driver/unbind
 
   # Load VFIO Kernel Module
   modprobe vfio
@@ -211,12 +189,11 @@ bind_vfio_pci() {
   modprobe vfio_pci
 
   # GPU 1 bind to vfio-pci
-  echo "$GPU_VIDEO_1" > /sys/bus/pci/drivers/vfio-pci/bind
-  echo "$GPU_AUDIO_1" > /sys/bus/pci/drivers/vfio-pci/bind
+  echo "$GUEST_GPU_VIDEO_BUS_ID" > /sys/bus/pci/drivers/vfio-pci/bind
+  echo "$GUEST_GPU_AUDIO_BUS_ID" > /sys/bus/pci/drivers/vfio-pci/bind
 }
 
-# TODO Generic name bind_gpu_driver
-bind_nvidia() {
+bind_guest_gpu_driver() {
   # Unbind VTconsoles
   echo 0 > /sys/class/vtconsole/vtcon0/bind
   echo 0 > /sys/class/vtconsole/vtcon1/bind
@@ -228,12 +205,12 @@ bind_nvidia() {
   sleep 4
 
   # GPU 1 unbind from vfio-pci
-  echo "$GPU_VIDEO_1" > /sys/bus/pci/devices/$GPU_VIDEO_1/driver/unbind
-  echo "$GPU_AUDIO_1" > /sys/bus/pci/devices/$GPU_AUDIO_1/driver/unbind
+  echo "$GUEST_GPU_VIDEO_BUS_ID" > /sys/bus/pci/devices/$GUEST_GPU_VIDEO_BUS_ID/driver/unbind
+  echo "$GUEST_GPU_AUDIO_BUS_ID" > /sys/bus/pci/devices/$GUEST_GPU_AUDIO_BUS_ID/driver/unbind
 
   # GPU 1 bind to nvidia
-  echo "$GPU_VIDEO_1" > /sys/bus/pci/drivers/nvidia/bind
-  echo "$GPU_AUDIO_1" > /sys/bus/pci/drivers/snd_hda_intel/bind
+  echo "$GUEST_GPU_VIDEO_BUS_ID" > /sys/bus/pci/drivers/nvidia/bind
+  echo "$GUEST_GPU_AUDIO_BUS_ID" > /sys/bus/pci/drivers/snd_hda_intel/bind
 
   # TODO Maybe?
   # nvidia-xconfig --query-gpu-info > /dev/null 2>&1
@@ -253,18 +230,27 @@ bind_nvidia() {
 
 case $1 in
   -h|help)
-    echo "Valid arguments are \"egpu\", \"internal\", \"boot\", \"remove\" or \"setup\"."
-    echo "Example: sudo gswitch egpu"
+    echo "Valid arguments are \"guest\", \"host\", \"boot\", \"remove\" or \"setup\"."
+    echo "Example: sudo gswitch guest"
     exit 0
   ;;
-  egpu)
-    switch_egpu
-  ;;
-  internal)
-    switch_internal
+  host|guest)
+    if ! has_xorg_confs_setup; then
+      echo "GPU Xorg configs are missing, please run setup before use:"
+      echo "# gswitch setup"
+      exit 1
+    fi
+    case $1 in
+      host)
+        switch_to_host_gpu
+      ;;
+      guest)
+        switch_to_guest_gpu
+      ;;
+    esac
   ;;
   boot)
-    MODE="internal"
+    MODE="host"
     for HEX_ID in $(lspci | grep -i 'vga' | cut -f 1 -d ' '); do
       DEC_ID=""
       for HEX_VALUE in $(echo "${HEX_ID}" | tr ':|\.' ' '); do
@@ -273,35 +259,38 @@ case $1 in
         DEC_ID="${DEC_ID}:${DEC_VALUE}"
       done
       DEC_ID=$(echo "${DEC_ID}" | sed 's/^://')
-      if [ "${DEC_ID}" = "${EGPU_BUS_ID}" ]; then
-        MODE="egpu"
+      if [ "${DEC_ID}" = "${GUEST_GPU_BUS_ID}" ]; then
+        MODE="guest"
         break
       fi
     done
     case ${MODE} in
-      egpu)
+      guest)
+        # TODO
         if [ "${EGPU_SET}" = "true" ]; then
-          echo "no" | switch_egpu
+          echo "no" | switch_to_guest_gpu
         else
-          echo "yes" | switch_egpu
+          echo "yes" | switch_to_guest_gpu
         fi
       ;;
-      internal)
+      host)
+        # TODO
         if [ "${EGPU_SET}" = "true" ]; then
-          echo "yes" | switch_internal
+          echo "yes" | switch_to_host_gpu
         else
-          echo "no" | switch_internal
+          echo "no" | switch_to_host_gpu
         fi
       ;;
     esac
   ;;
   remove)
-    BUS1D=$(echo "${EGPU_BUS_ID}" | cut -f 1 -d :)
-    BUS2D=$(echo "${EGPU_BUS_ID}" | cut -f 2 -d :)
+    BUS1D=$(echo "${GUEST_GPU_BUS_ID}" | cut -f 1 -d :)
+    BUS2D=$(echo "${GUEST_GPU_BUS_ID}" | cut -f 2 -d :)
     BUS1H=$(printf "%02x" "${BUS1D}")
     BUS2H=$(printf "%02x" "${BUS2D}")
     HEX_DID="${BUS1H}:${BUS2H}."
     DEV_PATH="/sys/bus/pci/devices/[0-9a-f:]*${HEX_DID}[0-9]*/remove"
+    # TODO
     echo "Try removing the GPU PCIe addresses? This will switch to internal and log you out. (Beta) (Y/n): "
     read -r REMOVE_ANSWER
     case "${REMOVE_ANSWER}" in
@@ -316,44 +305,34 @@ case $1 in
         exit 1
       ;;
     esac
-  echo "yes" | switch_internal
+  echo "yes" | switch_to_host_gpu
   ;;
   setup)
-    cp /usr/share/gswitch/xorg.conf.egpu "${EGPU_TEMPLATE}"
-    lspci | awk '/vga|VGA/{print "BusID: "$0}'
-    echo "Which of these cards is your eGPU?"
-    echo "Please type in the BusID, e.g: 00:02.0"
-    read -r HEX_ID
-    VALID_HEX_ID=$(echo "${HEX_ID}" | grep -Ec '^[a-z0-9]+:[a-z0-9]+\.[a-z0-9]$')
-    if [ "${VALID_HEX_ID}" -ne 1 ]; then
-      echo "You have typed in an unvalid BusID."
-      echo "Example of valid entry: 00:02.0"
-      exit 1
-    fi
-    for HEX_VALUE in $(echo "${HEX_ID}" | tr ':|\.' ' '); do
-      HEX_VALUE_UPPER=$(echo "${HEX_VALUE}" | tr '[:lower:]' '[:upper:]')
-      DEC_VALUE=$(echo "ibase=16; ${HEX_VALUE_UPPER}" | bc)
-      DEC_ID="${DEC_ID}:${DEC_VALUE}"
+    # TODO Validation of conf file being read from
+    GPU_NAMES=("host" "guest")
+    GPU_BUS_IDS=("${HOST_GPU_VIDEO_BUS_ID}" "${GUEST_GPU_VIDEO_BUS_ID}")
+    GPU_DRIVERS=("${HOST_GPU_DRIVER}" "${GUEST_GPU_DRIVER}")
+    # Assume default host gpu currently in use, set guest gpu conf to skip
+    XORG_CONFS=("${XORG_HOST_GPU_CONF}" "${XORG_GUEST_GPU_CONF}.skip")
+    for (( i=0; i < ${#GPU_NAMES[@]}; i++)); do
+      GPU_NAME="${GPU_NAMES[$i]}"
+      XORG_CONF="${XORG_CONFS[$i]}"
+      GPU_BUS_ID="${GPU_BUS_IDS[$i]}"
+      GPU_DRIVER="${GPU_DRIVERS[$i]}"
+
+      DEC_ID="PCI:$(hex_bus_id_to_dec_id "${GPU_BUS_ID}")"
+      cp /usr/share/gswitch/xorg.template.conf "${XORG_CONF}"
+      sed -E -i "s/BusID.*$/BusID      \"${DEC_ID}\"/" "${XORG_CONF}"
+      GPU_ID=$(lspci | grep -i "${HEX_ID}")
+      sed -E -i "s/Driver.*$/Driver     \"${GPU_DRIVER}\"/" "${XORG_CONF}"
     done
-    DEC_ID=$(echo "${DEC_ID}" | sed 's/^:/PCI:/')
-    sed -E -i "s/BusID.*$/BusID      \"${DEC_ID}\"/" "${EGPU_TEMPLATE}"
-    GPU_ID=$(lspci | grep -i "${HEX_ID}")
-    if echo "${GPU_ID}" | grep -qi 'nvidia'; then
-      DRIVER="nvidia"
-    elif echo "${GPU_ID}" | grep -qi 'amd'; then
-      DRIVER="amdgpu"
-    else
-      echo "Couldn't automatically find the proper driver for the GPU. Exiting."
-      exit 1
-    fi
-    sed -E -i "s/Driver.*$/Driver     \"${DRIVER}\"/" "${EGPU_TEMPLATE}"
     echo "Setup complete!"
     exit 0
   ;;
   *)
     echo "Unknown argument: ${1}."
-    echo "Valid arguments are \"egpu\", \"internal\", \"boot\", \"remove\" or \"setup\"."
-    echo "Example: sudo gswitch egpu"
+    echo "Valid arguments are \"guest\", \"host\", \"boot\", \"remove\" or \"setup\"."
+    echo "Example: sudo gswitch guest"
     exit 1
   ;;
 esac
